modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "${license}"
issueTrackerURL= "${tracker}"
displayURL="${home_page}"
[[mods]]
modId = "fixmcstats"
version = "${version}"
displayName = "${mod_name}"
logoFile="/assets/${mod_id}/${mod_id}.png"
credits="${credits}"
authors = "${mod_author}"
description = '''${description}'''
[[mixins]]
config = "${mod_id}.mixins.json"
[[mixins]]
config = "${mod_id}.neoforge.mixins.json"
[[dependencies.${mod_id}]]
modId = "neoforge"
type="required"
versionRange = "[${neoforge_version},)"
ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "BOTH" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'
[[dependencies.${mod_id}]]
modId = "minecraft"
type="required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"